### ISSUE TITLE
Panic while enumerating displays on release builds

### ISSUE THREAD

**Issue by janderholm** [arcnmx/ddcset-rs#1]
Running ddcset built with --release on rust 1.25 (I have not tested anything else) results in a panic:

```
$ cargo run --release -- capabilities

    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/ddcset capabilities`
thread 'main' panicked at 'assertion failed: start <= end && end <= self.len()', /home/johan/.cargo/registry/src/github.com-1ecc6299db9ec823/resize-slice-0.1.2/src/lib.rs:51:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:396
             at libstd/panicking.rs:576
   3: std::panicking::begin_panic
   4: <ddc_i2c::enumerate::Enumerator as core::iter::iterator::Iterator>::next
   5: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
   6: ddcset::displays
   7: ddcset::main_result
   8: ddcset::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: _start
```

Building debug works a little better, I get the following error message:

```
$ cargo run -- capabilities
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/ddcset capabilities`
Display on i2c-dev:
        ID: 22784
ERROR 2018-05-09T15:38:00Z: ddcset: Failed to get capabilities: DDC/CI error: DDC/CI checksum mismatch
```

However `getvcp 10` works so it might be something with my monitor:

```
cargo run -- getvcp 10
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/ddcset getvcp 10`
Display on i2c-dev:
        ID: 22784
        Feature 0x10 = 80 / 100
```

**Comment by arcnmx** [comment]
Thanks for the report and for trying it out! I can reproduce the panic and will look into it on my end.

I cannot however reproduce the checksum mismatch, which could be a number of issues. Which video driver are you using? For comparison could you maybe try ddcutil (`ddcutil capabilities`) as a sanity check? I should probably look into adding more verbose logging so `RUST_LOG=trace` can be used to display exactly what's going on over I2C, as it's hard to diagnose without seeing the bus traffic.

EDIT: [panic fixed in a dependency](https://github.com/arcnmx/ddcset-rs/commit/b0fa78985a1f62a6aa687b44538ffaa1b069d88a)

**Comment by arcnmx** [comment]
Closing as the panic has been fixed; feel free to reopen/resubmit with more info if the bus issues are still relevant.
